In [1]:
import pandas as pd
import numpy as np

In [2]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [3]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [4]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [5]:
a1=np.arange(10,dtype=np.int32)

In [6]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [7]:
a2=np.arange(10,dtype=np.int64)

In [8]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a3 = np.arange(12,dtype=float)
a3

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [10]:
a3 = np.arange(12,dtype=float).reshape(3,4)
a3

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [11]:
a4 = np.arange(8,dtype=float).reshape(2,2,2)
a4

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [12]:
a3.ndim

2

In [13]:
a4.ndim

3

In [14]:
a2.size

10

In [15]:
a3.size

12

In [16]:
a3.dtype

dtype('float64')

In [17]:
a4.dtype


dtype('float64')

In [18]:
a2.dtype

dtype('int64')

In [19]:
a2**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [20]:
a1.itemsize

4

In [21]:
a1.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [22]:
a2.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a3.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [24]:
arr = np.random.randint(0,10, (3,3))

In [25]:
arr

array([[2, 1, 5],
       [4, 6, 1],
       [1, 7, 2]], dtype=int32)

In [26]:
arr.T

array([[2, 4, 1],
       [1, 6, 7],
       [5, 1, 2]], dtype=int32)

In [27]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [28]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr1.sum()

np.int64(45)

In [30]:
arr1.min()

np.int64(1)

In [31]:
arr1.max()

np.int64(9)

In [32]:
arr1.mean()

np.float64(5.0)

In [33]:
np.std(arr1)

np.float64(2.581988897471611)

In [34]:
np.var(arr1)

np.float64(6.666666666666667)

In [35]:
np.cumsum(arr1)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [36]:
np.cumsum(arr1,axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [37]:
np.argmax(arr1)

np.int64(8)

In [38]:
np.argmin(arr1)

np.int64(0)

In [39]:
np.transpose(arr1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [40]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [41]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

In [42]:
arr2 = np.array([[7,8,9],
                 [10,11,12]])

In [43]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [45]:
arr1 + arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [46]:
arr3 = np.array([[7,8],
                 [10,11],
                 [1,3]])

In [47]:
arr3

array([[ 7,  8],
       [10, 11],
       [ 1,  3]])

In [48]:
arr1 - arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [49]:
arr1 * arr2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [50]:
arr1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [51]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [52]:
arr1

array([[1, 1, 1],
       [1, 2, 2],
       [1, 1, 1]], dtype=int32)

In [53]:
arr2

array([[1, 2, 1],
       [2, 2, 2],
       [2, 2, 1]], dtype=int32)

In [54]:
arr1 @ arr2

array([[ 5,  6,  4],
       [ 9, 10,  7],
       [ 5,  6,  4]], dtype=int32)

In [55]:
arr1 * arr2

array([[1, 2, 1],
       [2, 4, 4],
       [2, 2, 1]], dtype=int32)

In [56]:
np.dot(arr1,arr2)

array([[ 5,  6,  4],
       [ 9, 10,  7],
       [ 5,  6,  4]], dtype=int32)

In [57]:
np.matmul(arr1,arr2)

array([[ 5,  6,  4],
       [ 9, 10,  7],
       [ 5,  6,  4]], dtype=int32)

In [58]:
arr1 > arr2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [59]:
arr2 > arr1

array([[False,  True, False],
       [ True, False, False],
       [ True,  True, False]])

In [60]:
arr1 == arr2

array([[ True, False,  True],
       [False,  True,  True],
       [False, False,  True]])

In [63]:
a=np.array([1,234,343,4356,5])

In [64]:
a[3]

np.int64(4356)

In [65]:
a[2]

np.int64(343)

In [66]:
a[1:3]

array([234, 343])

In [67]:
a1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [68]:
a1[2,2]

np.int64(9)

In [69]:
a1[1,2]

np.int64(6)

In [70]:
a1[1,1]

np.int64(5)

In [71]:
a1[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [72]:
arr = np.array([1,2,3,4,5])

for i in arr:
    print(i)

1
2
3
4
5


In [73]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

for i in a:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [74]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [75]:
for row in a:
    for e in row:
        print(e)

1
2
3
4
5
6
7
8
9


In [76]:
for row in a:
    for e in row:
        print(e,end = " ")

1 2 3 4 5 6 7 8 9 

In [77]:
for row in a:
    for e in row:
        print(e,end = " ")

    print()

1 2 3 
4 5 6 
7 8 9 


In [78]:
for e in np.nditer(a):
    print(e, end=" ")

1 2 3 4 5 6 7 8 9 

In [79]:
def row_sum(row):
    return np.sum(row)

a=np.apply_along_axis(row_sum,1,a)
print(a)

[ 6 15 24]


In [81]:
pd.DataFrame(a)

0
0   6
1  15
2  24

In [82]:
print("The End")

The End
